name: Build and Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Increment Patch Version
        run: |
           find /home/runner/work/maven-hello-world/maven-hello-world -type d -name "myapp"

           #ls /home/runner/work/maven-hello-world/maven-hello-world
           #ls ${{ github.workspace }}
           #cd /home/runner/work/maven-hello-world/maven-hello-world/myapp
           #ls
           #cd ${{ github.workspace }}/myapp
           #mvn versions:set -DnewVersion=[$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout).nextIncrementalVersion]
