name: Build and Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker version
        run: docker --version


      - name: Increment Patch Version
        run: |
          cd /home/runner/work/maven-hello-world/maven-hello-world/myapp
          mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{print $1"."$2"."$3+1}')
        #run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml versions:set -DnewVersion=\$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{print $1"."$2"."$3+1}')

      - name: Compile Java Source Code
        run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml compile


      - name: Run Tests
        run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml test -Dtest=com.myapp.AppTest


      - name: Package Artifact
        run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml package


      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/*.jar


      - name: Build Docker Image
        run: |
          cd /home/runner/work/maven-hello-world/maven-hello-world/myapp
          docker build -t java-app .
          docker images | grep java-app

      - name: grep docker
        run: docker images | grep java-app


      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Tag Docker Image
        run: docker tag java-app java-app:${{ steps.Increment_Version.outputs.new_version }}

      - name: Push Docker image with version tag
        run: docker push java-app:${{ steps.Increment_Version.outputs.new_version }}


      - name: Tag Docker image with latest
        run: docker image tag java-app:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest

      - name: Push Docker image with latest tag
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
