name: Build and Deploy Pipeline

on:
  push:
    branches:
      - fix

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          # Extract version information from pom.xml
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          # Build Docker image with tag based on Maven project version
          docker build -t kupidun/java-app:$VERSION .
          
          # Login to DockerHub
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          # Push the Docker image with version tag and latest tag
          docker push kupidun/java-app:$VERSION
          docker tag kupidun/java-app:$VERSION kupidun/java-app:latest
          docker push kupidun/java-app:latest
        working-directory: ./myapp
