name: Build and Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker version
        run: docker --version
      - name: Increment Patch Version
        run: |
          cd /home/runner/work/maven-hello-world/maven-hello-world/myapp
          #Getting the current Versino from the pom.xml file
          current_version=$(grep -oP '<version>\K[^<]+' pom.xml)
          #Increment the last section of the semntic schme verions
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          #Actually update the version insde the pom file
          #awk -v current_version="$current_version" -v new_version="$new_version" 'gsub("<version>" current_version "</version>", "<version>" new_version "</version>")' pom.xml > temp && mv temp pom.xml

      - name: Compile Java Source Code
        run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml compile


      - name: Run Tests
        run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml test -Dtest=com.myapp.AppTest

      - name: Package Artifact
        run: mvn -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml package


      - name: Build Docker Image
        run: |
          cd /home/runner/work/maven-hello-world/maven-hello-world/myapp
          #VERSION=$(grep -oP '<version>\K[^<]+' pom.xml)
          #docker build  VERSION=1.0.0 -t javaApp:$VERSION .
          docker build  VERSION=1.0.0 -t javaApp:$VERSION .
